// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// ResourceApplier is an autogenerated mock type for the ResourceApplier type
type ResourceApplier struct {
	mock.Mock
}

// Apply provides a mock function with given fields: resource
func (_m *ResourceApplier) Apply(resource *unstructured.Unstructured) error {
	ret := _m.Called(resource)

	var r0 error
	if rf, ok := ret.Get(0).(func(*unstructured.Unstructured) error); ok {
		r0 = rf(resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
