// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	schema "k8s.io/apimachinery/pkg/runtime/schema"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceManager is an autogenerated mock type for the ResourceManager type
type ResourceManager struct {
	mock.Mock
}

// CreateResource provides a mock function with given fields: resource, gvk, opts
func (_m *ResourceManager) CreateResource(resource *unstructured.Unstructured, gvk schema.GroupVersionKind, opts v1.CreateOptions) error {
	ret := _m.Called(resource, gvk, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(*unstructured.Unstructured, schema.GroupVersionKind, v1.CreateOptions) error); ok {
		r0 = rf(resource, gvk, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCollectionOfResources provides a mock function with given fields: gvk, opts, listOps
func (_m *ResourceManager) DeleteCollectionOfResources(gvk schema.GroupVersionKind, opts v1.DeleteOptions, listOps v1.ListOptions) error {
	ret := _m.Called(gvk, opts, listOps)

	var r0 error
	if rf, ok := ret.Get(0).(func(schema.GroupVersionKind, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(gvk, opts, listOps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetResource provides a mock function with given fields: resourceName, gvk, opts
func (_m *ResourceManager) GetResource(resourceName string, gvk schema.GroupVersionKind, opts v1.GetOptions) (*unstructured.Unstructured, error) {
	ret := _m.Called(resourceName, gvk, opts)

	var r0 *unstructured.Unstructured
	if rf, ok := ret.Get(0).(func(string, schema.GroupVersionKind, v1.GetOptions) *unstructured.Unstructured); ok {
		r0 = rf(resourceName, gvk, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, schema.GroupVersionKind, v1.GetOptions) error); ok {
		r1 = rf(resourceName, gvk, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateResource provides a mock function with given fields: resource, gvk, opts
func (_m *ResourceManager) UpdateResource(resource *unstructured.Unstructured, gvk schema.GroupVersionKind, opts v1.UpdateOptions) (*unstructured.Unstructured, error) {
	ret := _m.Called(resource, gvk, opts)

	var r0 *unstructured.Unstructured
	if rf, ok := ret.Get(0).(func(*unstructured.Unstructured, schema.GroupVersionKind, v1.UpdateOptions) *unstructured.Unstructured); ok {
		r0 = rf(resource, gvk, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*unstructured.Unstructured, schema.GroupVersionKind, v1.UpdateOptions) error); ok {
		r1 = rf(resource, gvk, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
