// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// ResourceParser is an autogenerated mock type for the ResourceParser type
type ResourceParser struct {
	mock.Mock
}

// ParseUnstructuredResourceFrom provides a mock function with given fields: path
func (_m *ResourceParser) ParseFile(path string) (*unstructured.Unstructured, error) {
	ret := _m.Called(path)

	var r0 *unstructured.Unstructured
	if rf, ok := ret.Get(0).(func(string) *unstructured.Unstructured); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
