// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SecretClient is an autogenerated mock type for the SecretClient type
type SecretClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *SecretClient) Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1.Secret, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *corev1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *corev1.Secret); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, configMap, opts
func (_m *SecretClient) Update(ctx context.Context, configMap *corev1.Secret, opts v1.UpdateOptions) (*corev1.Secret, error) {
	ret := _m.Called(ctx, configMap, opts)

	var r0 *corev1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Secret, v1.UpdateOptions) *corev1.Secret); ok {
		r0 = rf(ctx, configMap, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *corev1.Secret, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, configMap, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
