// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import meta "k8s.io/apimachinery/pkg/api/meta"
import mock "github.com/stretchr/testify/mock"
import schema "k8s.io/apimachinery/pkg/runtime/schema"

// RESTMapper is an autogenerated mock type for the RESTMapper type
type RESTMapper struct {
	mock.Mock
}

// RESTMapping provides a mock function with given fields: gk, versions
func (_m *RESTMapper) RESTMapping(gk schema.GroupKind, versions ...string) (*meta.RESTMapping, error) {
	_va := make([]interface{}, len(versions))
	for _i := range versions {
		_va[_i] = versions[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, gk)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *meta.RESTMapping
	if rf, ok := ret.Get(0).(func(schema.GroupKind, ...string) *meta.RESTMapping); ok {
		r0 = rf(gk, versions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.RESTMapping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.GroupKind, ...string) error); ok {
		r1 = rf(gk, versions...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
